Updated ReadMe
privacy-tech-lab/gpc-android pull request #93
Opened 2024-11-22 19:32 UTC by n-aggarwal

Updated Readme with updated instruction for running the Dynamic Analysis

2024-11-24 19:14 UTC, samir-cerrato requested changes
For Apps to Test: 
Once the repo is cloned, you will see there is a file called scripts/app-list.txt. In that file you should enter the list of package names that you want to test. Each package name should be on a new line. **_Make sure to leave add an empty line after your last package name._**

Frida Troubleshooting:
Maybe add the solution of deleting the Android run time library to fix the following Frida error we encountered before: 

{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:578:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":578,"columnNumber":1}

Steps to uninstall run time: 

1. Enter "pm uninstall com.google.android.art"
2. Reboot your device

2025-01-01 20:57 UTC, SebastianZimmeck commented
@n-aggarwal, can this be merged (after @samir-cerrato' changes)?

2025-01-02 11:47 UTC, n-aggarwal commented
> @n-aggarwal, can this be merged (after @samir-cerrato' changes)?

Yes, after Samir updates the Readme with the required changes, the branch can be merged.

2025-01-02 12:02 UTC, SebastianZimmeck commented
@samir-cerrato, can you update the readme?

2025-01-03 16:36 UTC, merged